CREATE TABLE services."order" (
          total_amount numeric(38, 2) NULL,
          id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
          order_date timestamp(6) NOT NULL,
          updated_at timestamp(6) NULL,
          customer_email varchar(255) NULL,
          payment_method varchar(255) NULL,
          reference varchar(255) NULL,
          status varchar(255) NULL,
          CONSTRAINT order_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['PAYPAL'::character varying, 'CREDIT_CARD'::character varying, 'VISA_CARD'::character varying, 'MASTER_CARD'::character varying, 'AMERICAN_EXPRESS'::character varying, 'DISCOVER_CARD'::character varying, 'APPLE_PAY'::character varying, 'GOOGLE_PAY'::character varying, 'AMAZON_PAY'::character varying, 'BITCOIN'::character varying])::text[]))),
	CONSTRAINT order_pkey PRIMARY KEY (id),
	CONSTRAINT order_status_check CHECK (((status)::text = ANY ((ARRAY['CANCELED'::character varying, 'COMPLETE'::character varying, 'CREATED'::character varying, 'IN_PROCESS'::character varying, 'FAILED_CREATION'::character varying, 'PENDING_PAYMENT'::character varying, 'FAILED_PAYMENT'::character varying])::text[])))
);



CREATE TABLE services.order_line (
                                     line_total numeric(38, 2) NULL,
                                     price numeric(38, 2) NULL,
                                     quantity float8 NOT NULL,
                                     id int8 NOT NULL,
                                     order_id int8 NOT NULL,
                                     product_id int8 NULL,
                                     product_name varchar(255) NULL,
                                     CONSTRAINT order_line_pkey PRIMARY KEY (id),
                                     CONSTRAINT fk_order_line_order
                                         FOREIGN KEY (order_id)
                                             REFERENCES services."order"(id)
);

