CREATE TABLE services.payment (
                                  amount numeric(38, 2) NULL,
                                  id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                  last_modified_date timestamp(6) NULL,
                                  order_id int8 NULL,
                                  payment_date timestamp(6) NOT NULL,
                                  order_reference varchar(255) NULL,
                                  payment_method varchar(255) NULL,
                                  status varchar(255) NULL,
                                  CONSTRAINT payment_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['PAYPAL'::character varying, 'CREDIT_CARD'::character varying, 'VISA_CARD'::character varying, 'MASTER_CARD'::character varying, 'AMERICAN_EXPRESS'::character varying, 'DISCOVER_CARD'::character varying, 'APPLE_PAY'::character varying, 'GOOGLE_PAY'::character varying, 'AMAZON_PAY'::character varying, 'BITCOIN'::character varying])::text[]))),
	CONSTRAINT payment_pkey PRIMARY KEY (id),
	CONSTRAINT payment_status_check CHECK (((status)::text = ANY ((ARRAY['ACCEPTED'::character varying, 'DENIED'::character varying])::text[])))
);
