CREATE TABLE services.product_category (
                                           id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                           description varchar(255) NULL,
                                           "name" varchar(255) NULL,
                                           CONSTRAINT product_category_name_key UNIQUE (name),
                                           CONSTRAINT product_category_pkey PRIMARY KEY (id)
);

CREATE TABLE services.product (
                      available_quantity float8 NOT NULL,
                      price numeric(38, 2) NULL,
                      category_id int8 NULL,
                      id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                      description varchar(255) NULL,
                      "name" varchar(255) NULL,
                      CONSTRAINT product_name_key UNIQUE (name),
                      CONSTRAINT product_pkey PRIMARY KEY (id),
                      CONSTRAINT fk_product_category_product
                          FOREIGN KEY (category_id)
                              REFERENCES services.product_category(id)
);






