CREATE TABLE services.users_role (
    created_at DATE,
    updated_at DATE,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE
    CHECK (name IN ('USER', 'ADMIN', 'OWNER'))
);


CREATE TABLE services.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    email VARCHAR(255) UNIQUE,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT fk_users_role
       FOREIGN KEY (role_id)
       REFERENCES services.users_role(id)
    ON DELETE RESTRICT
);


INSERT INTO services.users_role (name, description, created_at, updated_at)
VALUES
    (
        'USER',
        'can access the authenticated user details for Default user',
        CURRENT_DATE,
        CURRENT_DATE
    ),
    (
        'ADMIN',
        'can access authenticated user details and list all users for administrator',
        CURRENT_DATE,
        CURRENT_DATE
    ),
    (
        'OWNER',
        'has access to all endpoints, including creating an administrator for owner',
        CURRENT_DATE,
        CURRENT_DATE
    )
    ON CONFLICT (name) DO NOTHING;